name: Alpha Release UI Kit Docs

on:
  push:
    branches:
      - master
      - alpha
      - chore/docs-deploy

jobs:
  alpha-release-ui-kit-docs:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, '(docs)')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set Git Configulations
        run: |
          git config --global user.email "lubycon@gmail.com"
          git config --global user.name "lubycon"
      - name: Caching Node Modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Caching Gatsby Build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-alpha-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-alpha-build-
      - name: Install depedencies
        run: yarn
      - name: Build
        run: yarn workspace lubycon-ui-kit-docs build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      - name: Publish
        run: yarn workspace lubycon-ui-kit-docs deploy
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ENV: 'alpha'
      - uses: 8398a7/action-slack@v3 # 슬랙 노티피케이션
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOY_BOT_WEBHOOK_URL }}
        if: always()
        