name: Publish Live Storybook

on:
  push:
    branches:
      - main

jobs:
  storybook-publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && contains(github.event.head_commit.message, '(docs)')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set Git Configulations
        run: |
          git config --global user.email "lubycon@gmail.com"
          git config --global user.name "lubycon"
      - name: Caching Node Modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install depedencies
        run: yarn
      - name: Build Storybook
        run: yarn build-stories
      - name: Publish
        run: yarn publish-stories
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ENV: 'live'
        